var severeDataJson = { 
	"type":"FeatureCollection",
    "features":[
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.01,
                    36.64
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROBERTSON",
                "state":"TN",
                "location":"5 NE ADAMS",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF-1 TORNADO TOUCHED DOWN A HALF MILE SOUTH OF THE KY/TN STATE LINE BETWEEN HUGH GILL ROAD AND KEYSBURG ROAD AND MOVED NORTHEAST WITH NUMEROUS TREES SNAPPED OR UPROO (OHX)",
                "timeReported":"2153",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.01,
                    36.64
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"KY",
                "location":"1 S KEYSBURG",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 1 FATAL... 1 INJ *** AN EF-2 TORNADO WITH MAX WINDS OF 135 MPH TOUCHED DOWN NEAR THE KY/TN STATE LINE ON MCGHEE ROAD. THE TORNADO THEN TRAVELED NE TO DOT ROAD WHERE (LMK)",
                "timeReported":"2154",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.95,
                    36.66
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"KY",
                "location":"1 S DOT",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 1 FATAL *** HOME DESTROYED BY APPARENT TORNADO. (LMK)",
                "timeReported":"2205",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.14,
                    37.02
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"1 SSW HAYS",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF-1 TORNADO WITH MAXIMUM ESTIMATED WINDS OF 100 MPH TOUCHED DOWN ON HAYS PONDSVILLE ROAD ABOUT 1 MILE SSW OF HAYS. THE TORNADO THEN TRAVELED NE JUST ACROSS THE WARR (LMK)",
                "timeReported":"2319",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.55,
                    36.32
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CLAY",
                "state":"AR",
                "location":"3 E KNOBEL",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 1 FATAL *** POSSIBLE TORNADO. A TRAILER WAS BLOWN INTO A POND NEAR HIGHWAY 90 EAST OF HIGHWAY 135. ONE FATALITY REPORTED. (MEG)",
                "timeReported":"2330",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.05,
                    35.7
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MISSISSIPPI",
                "state":"AR",
                "location":"3 W OSCEOLA",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"ROOF RIPPED OFF HOTEL... CONSIDERABLE DAMAGE. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"0014",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.58,
                    36.76
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"NEW MADRID",
                "state":"MO",
                "location":"MATTHEWS",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 2 INJ *** NWS STORM SURVEY REVEALS EF-2 TORNADO DAMAGE OCCURRED FROM SOUTH SIDE OF MATTHEWS TO 1 MILE EAST OF TOWN. PATH LENGTH OF 1 MILE WITH MAX WIDTH OF 150 YARD (PAH)",
                "timeReported":"0030",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.01,
                    36.45
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"OBION",
                "state":"TN",
                "location":"3 NE UNION CITY",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 3 INJ *** POSSIBLE TORNADO. 10 PEOPLE WERE RESCUED FROM SEVERAL DAMAGED STRUCTURES AROUND THE AREA. THREE INDIVIDUALS WERE TRANSPORTED TO HOSPITAL WITH UNKNOWN INJU (MEG)",
                "timeReported":"0102",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.64,
                    37.02
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MCCRACKEN",
                "state":"KY",
                "location":"2 SE LONE OAK",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"UPDATED INFORMATION. EF1 TORNADO BEGAN SOUTH OF KREBS STATION RD AND ENDED NORTH OF CLARKS LINE RD. TORNADO DESTROYED A BARN. THREE HOMES AND A GARAGE WERE DAMAGED. PAT (PAH)",
                "timeReported":"0134",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.51,
                    36.53
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GRAVES",
                "state":"KY",
                "location":"1 SW BELL CITY",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"PEAK WINDS ESTIMATED NEAR 100 MPH. EF-1 TORNADO TRACKED FROM SOUTHEAST GRAVES INTO WEST CALLOWAY COUNTIES. PATH LENGTH 8.5 MILES. PATH WIDTH 125 YARDS. MORE THAN A HALF (PAH)",
                "timeReported":"0137",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.64,
                    37.02
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MCCRACKEN",
                "state":"KY",
                "location":"2 SE LONE OAK",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"BRIEF EF-0 TOUCHED DOWN AND UPROOTED A FEW PINE TREES. A FEW SHINGLES WERE OFF A HOUSE AND GARAGE. PEAK WINDS NEAR 65 MPH. PATH LENGTH ABOUT 0.15 MILE. PATH WIDTH 50 YA (PAH)",
                "timeReported":"0138",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.51,
                    36.74
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GRAVES",
                "state":"KY",
                "location":"1 WNW GOLO",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"EF1 TORNADO.TORNADO TOUCHED DOWN ON BILL RILEY RD AND BLEW SOME SHINGLES OFF A ROOF AND UPROOTED OR SNAPPED TREES. TORNADO CONTINUED NORTHEAST AND DAMAGED TREES ALONG T (PAH)",
                "timeReported":"0142",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.32,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CALLOWAY",
                "state":"KY",
                "location":"SW MURRAY",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"NWS STORM SURVEY REVEALS EF-1 TORNADO WITH PEAK WINDS OF 105 MPH OCCURRED IN SOUTH PART OF MURRAY. PATH LENGTH ABOUT 1.5 MILES. MAX PATH WIDTH ABOUT 100 YARDS. AT LEAST (PAH)",
                "timeReported":"0151",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.59,
                    36.67
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"SIMPSON",
                "state":"KY",
                "location":"4 SSW FRANKLIN",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"THE TORNADO BEGAN JUST SOUTHWEST OF LAKE SPRING ROAD WHERE A COUPLE OF TREES WERE SNAPPED OR UPROOTED AND A LARGE 24 X 36 BARN EXPERIENCED EXTENSIVE ROOF PANEL DAMAGE. (LMK)",
                "timeReported":"0235",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.47,
                    36.83
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"2 SE HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 9 INJ *** NWS STORM SURVEY REVEALS EF-2 TORNADO WITH PEAK WINDS OF 135 MPH OCCURRED FROM THE SOUTH SIDE OF HOPKINSVILLE TO 5.5 MILES EAST OF HOPKINSVILLE. PATH LENG (PAH)",
                "timeReported":"0244",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.49,
                    36.9
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"3 N HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"EF-0 TORNADO TRACKED 5.5 MILES ACROSS LAKE MORRIS AREA. PATH WIDTH 75 YARDS. PEAK WINDS 85 MPH. AT LEAST FOUR BARNS OR SHEDS WERE DAMAGED... PRIMARILY DUE TO PARTIAL LO (PAH)",
                "timeReported":"0244",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.47,
                    36.49
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MONTGOMERY",
                "state":"TN",
                "location":"8 SW CLARKSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF-1 TORNADO TOUCHED DOWN NEAR THE DOTSONVILLE COMMUNITY AND MOVED NORTHEAST ENDING ALONG THE CUMBERLAND RIVER JUST WEST OF CLARKSVILLE. A FEW HOMES SUFFERED ROOF DA (OHX)",
                "timeReported":"0250",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.29,
                    36.95
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"NW OVIL",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"BRIEF EF-0 TORNADO TOUCHED DOWN ALONG HIGHWAY 189 ABOUT A MILE WEST OF THE TODD COUNTY LINE. PEAK WINDS 65 MPH. PATH LENGTH 0.5 MILE. PATH WIDTH 50 YARDS. TWO GARAGES A (PAH)",
                "timeReported":"0255",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.27,
                    36.55
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MONTGOMERY",
                "state":"TN",
                "location":"4 E CLARKSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 2 INJ *** AN EF2 TORNADO TOUCHED DOWN IN EAST CLARKSVILLE ON DUNBAR CAVE RD THEN MOVED ENE ACROSS I-24 BEFORE ENDING ON KIRKWOOD RD. TREES WERE BLOWN DOWN N OF DUNB (OHX)",
                "timeReported":"0303",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.21,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MONTGOMERY",
                "state":"TN",
                "location":"8 ENE CLARKSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"*** 2 INJ *** SIGNIFICANT HOME DAMAGE IN THE FARMINGTON SUBDIVISION EAST OF CLARKSVILLE. HEAVY DAMAGE TO A CHURCH. AT LEAST 2 INJURED. (OHX)",
                "timeReported":"0306",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.97,
                    37.02
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"KY",
                "location":"2 NNW LEWISBURG",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF-1 TORNADO WITH MAX WINDS OF 110 MPH TOUCHED DOWN NEAR ELAMON ROAD ABOUT 2 MILES NNW OF LEWISBURG. IT THEN TRAVELED ESE ACROSS LEWISBURG ROAD BEFORE LIFTING. THE T (LMK)",
                "timeReported":"0315",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.04,
                    36.59
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROBERTSON",
                "state":"TN",
                "location":"2 ENE ADAMS",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF1 TORNADO TOUCHED DOWN EAST OF ADAMS NEAR JOHNSON SPRINGS ROAD AND MOVED NORTHEAST BEFORE ENDING ALONG BUZZARD CREEK ROAD. ONE HOME SUFFERED MINOR ROOF DAMAGE ON S (OHX)",
                "timeReported":"0319",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.87,
                    37.09
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BUTLER",
                "state":"KY",
                "location":"2 NW QUALITY",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"THE DAMAGE BEGAN NEAR EWING ROAD WHERE TREES WERE SNAPPED AND TWISTED. THIS CONTINUED ALONG GRAVELTOWN ROAD WHERE MORE TREES WERE TWISTED AND SNAPPED AND COUPLE WERE UP (LMK)",
                "timeReported":"0321",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.59,
                    36.67
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"SIMPSON",
                "state":"KY",
                "location":"4 SSW FRANKLIN",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"CORRECTS PREVIOUS TORNADO REPORT FROM 4 SSW FRANKLIN. THE TORNADO BEGAN JUST SOUTHWEST OF LAKE SPRING ROAD WHERE A COUPLE OF TREES WERE SNAPPED OR UPROOTED AND A LARGE (LMK)",
                "timeReported":"0350",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -85.62,
                    37.23
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GREEN",
                "state":"KY",
                "location":"3 N PIERCE",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF2 TORNADO WITH 110-115 MPH PEAK WINDS TOUCHED DOWN IN GREEN COUNTY KY NEAR THE TOWN OF GRAB. IT DAMAGED AND DOWNED MULTIPLE BARNS AND SNAPPED TREES ALONG ITS PATH. (LMK)",
                "timeReported":"0433",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.17,
                    38.83
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CLERMONT",
                "state":"OH",
                "location":"4 WSW FELICITY",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF1 TORNADO WAS CONFIRMED IN SOUTHERN CLERMONT COUNTY. THE TORNADO RESULTED IN NUMEROUS UPROOTED AND SNAPPED TREES AS WELL AS DAMAGE TO SOME PRIVATE PROPERTIES. (ILN)",
                "timeReported":"0503",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -83.96,
                    38.92
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BROWN",
                "state":"OH",
                "location":"5 NW GEORGETOWN",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"AN EF1 TORNADO WAS CONFIRMED IN WESTERN BROWN COUNTY. THE TORNADO RESULTED IN EXTENSIVE TREE DAMAGE AS WELL AS DAMAGE TO SEVERAL PRIVATE PROPERTIES. (ILN)",
                "timeReported":"0513",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.47,
                    37.63
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GARRARD",
                "state":"KY",
                "location":"3 WNW PAINT LICK",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"CORRECTS PREVIOUS TORNADO REPORT FROM 3 WNW PAINT LICK. A SMALL AND BRIEF EF1 TORNADO TOUCHED DOWN ON THE RIDGE OF GILLESPIE PIKE EAST OF LANCASTER. THE TORNADO FIRST U (LMK)",
                "timeReported":"0550",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.47,
                    37.63
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GARRARD",
                "state":"KY",
                "location":"3 WNW PAINT LICK",
                "marker-symbol":"default_marker",
                "eventType":"1",
                "comments":"A SMALL AND BRIEF EF1 TORNADO TOUCHED DOWN ON THE RIDGE OF GILLESPIE PIKE EAST OF LANCASTER. THE TORNADO FIRST UPROOTED A TREE... THEN CAME TO A SMALL SHED... WHICH IT (LMK)",
                "timeReported":"0650",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -95.53,
                    33.65
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LAMAR",
                "state":"TX",
                "location":"PARIS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL REPORTS OF WIND DAMAGE NEAR THE COMMUNITY OF HOPEWELL JUST NW OF PARIS---A FEW TREES DOWN... DAMAGE TO A CARPORT AND A BARN DESTROYED. EVENT LIKELY OCCURRED BET (FWD)",
                "timeReported":"1800",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -95.53,
                    33.65
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LAMAR",
                "state":"TX",
                "location":"PARIS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PEAK WIND GUST MEASURED AT THE PARIS/COX FIELD AWOS OF 60 KNOTS OR 69 M.P.H. (FWD)",
                "timeReported":"1812",
                "size":"69"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -95.13,
                    33.96
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MCCURTAIN",
                "state":"OK",
                "location":"4 SSW VALLIANT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"WOMAN CALLED THE SHERIFFS OFFICE TO REPORT THAT HALF OF HER HOUSE WAS GONE. (SHV)",
                "timeReported":"1824",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -95.1,
                    34.0
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MCCURTAIN",
                "state":"OK",
                "location":"VALLIANT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL TREES DOWN ACROSS THE CITY OF VALLIANT. (SHV)",
                "timeReported":"1826",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -95.01,
                    34.07
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MCCURTAIN",
                "state":"OK",
                "location":"WRIGHT CITY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"MEDIA REPORTS VIEWER STATED MULTIPLE TREE LIMBS DOWN AND ELECTRICITY FLASHING ON/OFF. NWS CHAT. (SHV)",
                "timeReported":"1840",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -94.33,
                    34.24
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"POLK",
                "state":"AR",
                "location":"GRANNIS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN IN THE TOWN OF GRANNIS (LZK)",
                "timeReported":"1911",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -94.24,
                    34.59
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"POLK",
                "state":"AR",
                "location":"MENA",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"(LZK)",
                "timeReported":"1920",
                "size":"60"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -93.77,
                    35.24
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"AR",
                "location":"DRIGGS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES AND POWERLINES DOWN IN DRIGGS. (LZK)",
                "timeReported":"1920",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -94.34,
                    34.05
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"SEVIER",
                "state":"AR",
                "location":"DE QUEEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ON VANDERVOORT DRIVE. (SHV)",
                "timeReported":"1925",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -93.95,
                    34.03
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HOWARD",
                "state":"AR",
                "location":"CENTER POINT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN BRINGING POWER LINES DOWN ON MADISON STREET IN CENTERPOINT. (SHV)",
                "timeReported":"2000",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -93.17,
                    34.32
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HOT SPRING",
                "state":"AR",
                "location":"BISMARCK",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES AND POWERLINES DOWN IN BISMARK. ROAD ALSO REPORTED TO BE WASHED OUT AT THE INTERSECTION OF HIGHWAYS 7 AND 84. (LZK)",
                "timeReported":"2106",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -92.8,
                    35.0
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"PERRY",
                "state":"AR",
                "location":"PERRYVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"(LZK)",
                "timeReported":"2124",
                "size":"60"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -92.44,
                    35.09
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"FAULKNER",
                "state":"AR",
                "location":"CONWAY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE S DOWN IN CONWAY... ONE TREE FELL ON A CAR. (LZK)",
                "timeReported":"2130",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -92.44,
                    35.09
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"FAULKNER",
                "state":"AR",
                "location":"CONWAY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE REPORTED TO BE BL0WN ONTO A HOUISE (LZK)",
                "timeReported":"2141",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.07,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROBERTSON",
                "state":"TN",
                "location":"2 N ADAMS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SIGNIFICANT DAMAGE TO AT LEAST 1 HOME NEAR KEYSBURG ROAD AND HUGH GILL ROAD FROM POSSIBLE TORNADO. (OHX)",
                "timeReported":"2150",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.04,
                    36.64
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROBERTSON",
                "state":"TN",
                "location":"4 NNE ADAMS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A HOUSE WAS DESTROYED AND OTHER DAMAGE OCCURRED FROM A POSSIBLE TORNADO NEAR THE INTERSECTION OF KEYSBURG ROAD... HUGH GILL ROAD... AND MCGEE ROAD. (OHX)",
                "timeReported":"2150",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -92.41,
                    34.54
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"SALINE",
                "state":"AR",
                "location":"1 N SARDIS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES REPORTED TO BE BLOWN DOWN (LZK)",
                "timeReported":"2207",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.85,
                    36.74
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"KY",
                "location":"5 SW CORINTH",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES AND POWER LINES DOWN. (LMK)",
                "timeReported":"2210",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -94.62,
                    32.51
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HARRISON",
                "state":"TX",
                "location":"3 W HALLSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"POWERLINES DOWN BETWEEN HALLSVILLE AND MARSHALL. (SHV)",
                "timeReported":"2220",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -91.49,
                    35.29
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WHITE",
                "state":"AR",
                "location":"WORDEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A NUMBER OF TREES WERE SNAPPED AND DOWNED. A CARPORT AND DECK SUSTAINED DAMAGE. (LZK)",
                "timeReported":"2226",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -91.9,
                    34.78
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LONOKE",
                "state":"AR",
                "location":"LONOKE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"LARGE DISPLAY TENT...WELL ANCHORED IN THE GROUND...WAS BLOWN OVER AT AN AUTO DEALERSHIP. (LZK)",
                "timeReported":"2235",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.99,
                    37.4
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CASEY",
                "state":"KY",
                "location":"4 SSE JACKTOWN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN... BRICK HOME ROOF DAMAGE... CAMPER TOSSED 6FT -8FT. (LMK)",
                "timeReported":"2235",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -91.9,
                    34.8
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LONOKE",
                "state":"AR",
                "location":"1 N LONOKE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES SNAPPED AND PART OF A METAL ROOF BLOWN OFF A HOME. (LZK)",
                "timeReported":"2236",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.99,
                    37.4
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CASEY",
                "state":"KY",
                "location":"4 SSE JACKTOWN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NWS STORM SURVEY FOUND DAMAGE CONSISTENT OF STRAIGHT LINE WINDS IN NORTHERN CASEY COUNTY. A PORCH AWNING WAS RIPPED OFF A HOME AND THROWN OVER THE ROOF INTO A FREE STAN (LMK)",
                "timeReported":"2240",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -91.41,
                    35.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"INDEPENDENCE",
                "state":"AR",
                "location":"3 ESE OIL TROUGH",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"(LZK)",
                "timeReported":"2246",
                "size":"63"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.96,
                    36.19
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"RANDOLPH",
                "state":"AR",
                "location":"MANSON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SIGNIFICANT DAMAGE TO METAL BUILDING AT LONG ROAD AND HIGHWAY 67. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"2300",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.95,
                    35.87
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CRAIGHEAD",
                "state":"AR",
                "location":"EGYPT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN IN WESTERN CRAIGHEAD COUNTY...EGYPT AREA. CORRECTED TIME (MEG)",
                "timeReported":"2315",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.12,
                    37.04
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BARREN",
                "state":"KY",
                "location":"1 NE HAYS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"REPORTED AT 2911 LEWIS ROAD... SMITHS GROVE... KY TREES DOWN AND STRUCTURAL DAMAGE. (LMK)",
                "timeReported":"2320",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.79,
                    35.4
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CROSS",
                "state":"AR",
                "location":"2 W CHERRY VALLEY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A HOME AND METAL SHOP BUILDING WERE DAMAGED ON HIGHWAY 42 BETWEEN HICKORY RIDGE AND CHERRY VALLEY. (MEG)",
                "timeReported":"2325",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.71,
                    35.99
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GREENE",
                "state":"AR",
                "location":"LORADO",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"ROOF BLOWN OFF OF BARN ON HIGHWAY 168. TIME ESTIMATED FROM RADAR. (MEG)",
                "timeReported":"2330",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.21,
                    36.39
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CLAY",
                "state":"AR",
                "location":"1 NW PIGGOTT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"2 HOUSES HAD THE ROOFS TORN OFF COMPLETELY ON COUNTY ROAD 341. (MEG)",
                "timeReported":"2330",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.7,
                    35.82
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CRAIGHEAD",
                "state":"AR",
                "location":"1 W JONESBORO",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN IN WEST JONESBORO. (MEG)",
                "timeReported":"2339",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.52,
                    35.67
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"POINSETT",
                "state":"AR",
                "location":"TRUMANN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"LIGHT POLES AND TREES DOWN IN THE TRUMANN AREA. TIME ADJUSTED BASED ON RADAR. (MEG)",
                "timeReported":"2340",
                "size":"70"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.95,
                    35.87
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CRAIGHEAD",
                "state":"AR",
                "location":"EGYPT",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN IN WESTERN CRAIGHEAD COUNTY... EGYPT AREA. (MEG)",
                "timeReported":"2340",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.52,
                    35.67
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"POINSETT",
                "state":"AR",
                "location":"TRUMANN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"LIGHT POLES AND TREES DOWN IN THE TRUMANN AREA. (MEG)",
                "timeReported":"2354",
                "size":"70"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.81,
                    35.83
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CRAIGHEAD",
                "state":"AR",
                "location":"5 S BONO",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PAVILLION DESTROYED NEAR BONO... MULTIPLE REPORTS OF WIND DAMAGE IN THE AREA. (MEG)",
                "timeReported":"2355",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.98,
                    36.58
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"DUNKLIN",
                "state":"MO",
                "location":"MALDEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"AT LEAST 20 STRUCTURES DAMAGED WITH INJURIES REPORTED. TIME ESTIMATED BY RADAR. POSSIBLE TORNADO. (MEG)",
                "timeReported":"0004",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -85.46,
                    38.22
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"JEFFERSON",
                "state":"KY",
                "location":"4 ESE MIDDLETOWN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"CORRECTS PREVIOUS TSTM WND DMG REPORT FROM 4 ESE MIDDLETOWN. TREES DOWN. (LMK)",
                "timeReported":"0010",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.56,
                    35.18
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CROSS",
                "state":"AR",
                "location":"GIESECK",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"POWER LINES DOWN ALONG HIGHWAY 75. (MEG)",
                "timeReported":"0015",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -90.09,
                    35.67
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MISSISSIPPI",
                "state":"AR",
                "location":"KEISER",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"DAMAGE TO FIRST BAPTIST CHURCH IN KEISER... BLOWN TRANSFORMERS... POWER LINES AND TREES DOWN. (MEG)",
                "timeReported":"0019",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.58,
                    36.76
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"NEW MADRID",
                "state":"MO",
                "location":"MATTHEWS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"REPORTS OF WINDOWS BLOWN OUT AND DAMAGE TO SEVERAL HOMES... CARS... AND AN OVERTURNED SEMI TRUCK IN MATTHEWS. (PAH)",
                "timeReported":"0050",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.58,
                    36.76
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"NEW MADRID",
                "state":"MO",
                "location":"MATTHEWS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"STRUCTURE AND WIND DAMAGE REPORTED NEAR MATTHEWS. (PAH)",
                "timeReported":"0055",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.69,
                    38.27
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GIBSON",
                "state":"IN",
                "location":"OWENSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NUMEROUS SMALL LIMBS AND SMALL TREES DOWN IN TOWN. WIND ESTIMATED AT LEAST 60 MPH. LATE REPORT. (PAH)",
                "timeReported":"0055",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.29,
                    36.31
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HENRY",
                "state":"TN",
                "location":"1 NE PARIS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"POWER POLES AND TREES DOWN ALONG INDIA AND MCINTOSH ROADS. (MEG)",
                "timeReported":"0100",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.01,
                    36.45
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"OBION",
                "state":"TN",
                "location":"3 NE UNION CITY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL HOMES DAMAGED AND POWER LINES DOWN. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"0102",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.23,
                    37.13
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"EDMONSON",
                "state":"KY",
                "location":"1 S RHODA",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"THE SURVEY CREW OBSERVED INTERMITTENT STRAIGHT-LINE WIND DAMAGE IN THE TOWN OF CHALYBEATE. THERE WAS DAMAGE TO FENCES... SEVERAL TREES SNAPPED... AND 2 OLDER BARNS EXPE (LMK)",
                "timeReported":"0103",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.02,
                    34.49
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"UNION",
                "state":"MS",
                "location":"NEW ALBANY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PUBLIC REPORTED DOWNED TREES AND A TRAILER DAMAGED. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"0108",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.22,
                    36.17
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"DYER",
                "state":"TN",
                "location":"3 SW TRIMBLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"MULTIPLE TREES DOWN ACROSS ROAD BETWEEN NEWBERN AND TRIMBLE. (MEG)",
                "timeReported":"0110",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.35,
                    35.24
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"FAYETTE",
                "state":"TN",
                "location":"SOMERVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SOME TREES DOWN AROUND THE COUNTY. (MEG)",
                "timeReported":"0130",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.56,
                    36.29
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WEAKLEY",
                "state":"TN",
                "location":"6 NNE GLEASON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"4 FOOT DIAMETER TREE DOWN ACROSS HIGHWAY 190... BLOCKING BOTH LANES. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"0142",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.69,
                    36.28
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WEAKLEY",
                "state":"TN",
                "location":"DRESDEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SOME TREES AND POWER LINES DOWN ACROSS THE COUNTY. (MEG)",
                "timeReported":"0145",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.32,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CALLOWAY",
                "state":"KY",
                "location":"MURRAY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"POWER OUTAGES REPORTED IN MURRAY AND AT THE MURRAY STATE CAMPUS. (PAH)",
                "timeReported":"0156",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.37,
                    36.84
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MARSHALL",
                "state":"KY",
                "location":"1 SW BENTON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE INSIDE A HOME ON THE SOUTHWEST SIDE OF BENTON. (PAH)",
                "timeReported":"0200",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.89,
                    36.92
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"TRIGG",
                "state":"KY",
                "location":"5 NW CADIZ",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE REPORTED DOWN BLOCKING BOTH LANES OF ROAD NEAR INTERSECTION OF REDDICK POND ROAD AND WILL JACKSON ROAD. TIME APPROXIMATED BY RADAR. (PAH)",
                "timeReported":"0220",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.91,
                    36.23
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HUMPHREYS",
                "state":"TN",
                "location":"10 E BIG SANDY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN AT 7600 GREENBRIER CREEK ROAD IN FAR NORTHWEST HUMPHREYS COUNTY (OHX)",
                "timeReported":"0222",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.32,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CALLOWAY",
                "state":"KY",
                "location":"MURRAY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"WIDESPREAD TREE DAMAGE... POWER OUTAGES... AND WINDOWS BLOWN OUT AT FOOD GIANT. (PAH)",
                "timeReported":"0222",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.76,
                    36.32
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HOUSTON",
                "state":"TN",
                "location":"TENNESSEE RIDGE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ON HIGHWAY 147 (OHX)",
                "timeReported":"0229",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.41,
                    36.01
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CARROLL",
                "state":"TN",
                "location":"HUNTINGDON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES AND POWER LINES DOWN ACROSS THE COUNTY. TREE DOWN ON HOUSE. (MEG)",
                "timeReported":"0230",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.1,
                    36.06
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BENTON",
                "state":"TN",
                "location":"N CAMDEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL TREES DOWN AND A FEW POWER POLES CAUSING POWER OUTAGES. (MEG)",
                "timeReported":"0230",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.76,
                    36.32
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HOUSTON",
                "state":"TN",
                "location":"TENNESSEE RIDGE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PORCH BLOWN OFF HOME (OHX)",
                "timeReported":"0230",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.72,
                    36.44
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"STEWART",
                "state":"TN",
                "location":"6 NW CUMBERLAND CITY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ON HIGHWAY 233 (OHX)",
                "timeReported":"0236",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.32,
                    36.61
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CALLOWAY",
                "state":"KY",
                "location":"MURRAY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREES DOWN AND ROOF DAMAGE ON 16TH ST. IN MURRAY. (PAH)",
                "timeReported":"0236",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.49,
                    36.85
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NUMEROUS BUILDINGS WITH DAMAGE INCLUDING A KMART AND THE SECOND STORY OF AN APARTMENT COMPLEX... SEVERAL POWER OUTAGES IN THE HOPKINSVILLE AREA. TIME APPROXIMATED BY RA (PAH)",
                "timeReported":"0245",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.76,
                    36.16
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HUMPHREYS",
                "state":"TN",
                "location":"5 NNE WAVERLY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ON HIGHWAY 13 (OHX)",
                "timeReported":"0247",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.35,
                    36.56
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MONTGOMERY",
                "state":"TN",
                "location":"CLARKSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"GROCERY STORE WINDOWS BLOWN OUT AND ROOF DAMAGE AT AUSTIN PEAY STATE UNIVERSITY IN CLARKSVILLE. AUSTIN PEAY/MURRAY STATE GAME IN CLARKSVILLE DELAYED BY SOME MINOR ROOF (OHX)",
                "timeReported":"0300",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.31,
                    36.59
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MONTGOMERY",
                "state":"TN",
                "location":"3 NE CLARKSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"LARGE TREE UPROOTED ON DUNBAR CAVE ROAD. (OHX)",
                "timeReported":"0303",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.95,
                    37.04
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LOGAN",
                "state":"KY",
                "location":"4 N LEWISBURG",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A TREE WAS BLOWN ACROSS COON RANGE LAKE ROAD. (LMK)",
                "timeReported":"0315",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.0,
                    36.59
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROBERTSON",
                "state":"TN",
                "location":"3 N CEDAR HILL",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL BARNS HAD SIGNIFICANT DAMAGE NEAR 5700 BUZZARD CREEK ROAD. (OHX)",
                "timeReported":"0320",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.49,
                    36.85
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NUMEROUS BUILDINGS WITH DAMAGE INCLUDING A KMART AND THE SECOND STORY OF AN APARTMENT COMPLEX... SEVERAL POWER OUTAGES IN THE HOPKINSVILLE AREA. (PAH)",
                "timeReported":"0321",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.85,
                    37.1
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BUTLER",
                "state":"KY",
                "location":"2 N QUALITY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A BARN WAS DAMAGED AND A LARGE TREE WAS UPROOTED ALONG HUNTSVILLE-QUALITY ROAD. (LMK)",
                "timeReported":"0321",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.49,
                    36.85
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"STRUCTURAL DAMAGE AT EAGLE CROSSING APARTMENTS ON CALVIN DRIVE. REPORTS OF MULTIPLE NON-LIFE-THREATENING INJURIES. (PAH)",
                "timeReported":"0334",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.57,
                    36.92
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"2 NW ROCKFIELD",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN. (LMK)",
                "timeReported":"0338",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.45,
                    36.99
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"1 NNW BOWLING GREEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ON POWER LINE... CORNER OF CABELL DR AND CHESTNUT ST. (LMK)",
                "timeReported":"0338",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.46,
                    36.98
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"BOWLING GREEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"(LMK)",
                "timeReported":"0343",
                "size":"69"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.43,
                    36.96
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"1 SE BOWLING GREEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PEAK WIND GUST AT BOWLING GREEN REGIONAL AIRPORT. (LMK)",
                "timeReported":"0344",
                "size":"58"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.4,
                    36.98
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WARREN",
                "state":"KY",
                "location":"2 ENE BOWLING GREEN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"REPORT OF TREE BLOCKING 2100 BLOCK OF MOUNT VICTOR LANE. (LMK)",
                "timeReported":"0345",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.48,
                    36.83
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CHRISTIAN",
                "state":"KY",
                "location":"2 SSE HOPKINSVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"ROOF DAMAGE TO THE AUDIO SPECIALISTS BUILDING ON FT. CAMPBELL BLVD. (PAH)",
                "timeReported":"0352",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.38,
                    36.08
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"DICKSON",
                "state":"TN",
                "location":"DICKSON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL REPORTS OF TREES DOWN COUNTY WIDE. (OHX)",
                "timeReported":"0354",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.18,
                    37.17
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"EDMONSON",
                "state":"KY",
                "location":"3 ENE RHODA",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"REPORTED AT HWY 70 NEAR MAMMOTH CAVE NATIONAL PARK TREE DOWN BLOCKING HWY 70 ON BOTH SIDES. (LMK)",
                "timeReported":"0354",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -85.86,
                    38.04
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"BULLITT",
                "state":"KY",
                "location":"5 S VALLEY STATION",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"DELAYED REPORT. TREES DOWN ON WEAVERS RUN RD. PART OF ROAD WASHED OUT. (LMK)",
                "timeReported":"0356",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.66,
                    34.71
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"PRENTISS",
                "state":"MS",
                "location":"JUMPERTOWN",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL TREES DOWN (MEG)",
                "timeReported":"0407",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -89.02,
                    34.49
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"UNION",
                "state":"MS",
                "location":"NEW ALBANY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"PUBLIC REPORTED DOWNED TREES AND A TRAILER DAMAGED. TIME ESTIMATED BY RADAR. (MEG)",
                "timeReported":"0408",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.53,
                    35.63
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HICKMAN",
                "state":"TN",
                "location":"6 NNE HOHENWALD",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"DELAYED TSPOTTER REPORT. 3 TO 4 TREES WERE BLOWN DOWN ONTO POWER LINES ALONG HIGHWAY 48 AROUND 1 MILE NORTH OF THE LEWIS COUNTY LINE. (OHX)",
                "timeReported":"0408",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.84,
                    34.64
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"TIPPAH",
                "state":"MS",
                "location":"DUMAS",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NUMEROUS LARGE TREES DOWN. (MEG)",
                "timeReported":"0415",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.12,
                    35.98
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WILLIAMSON",
                "state":"TN",
                "location":"FAIRVIEW",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"WIND GUSTS 65 MEASURED BY A HOME WEATHER STATION NEAR THE INTERSECTION OF HIGHWAY 100 AND BRUSH CREEK ROAD. (OHX)",
                "timeReported":"0415",
                "size":"65"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.9,
                    36.13
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"DAVIDSON",
                "state":"TN",
                "location":"3 NW BELLE MEADE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"WSMV NEWS CREW REPORTED TREE DOWN IN WEST NASHVILLE (OHX)",
                "timeReported":"0420",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.76,
                    35.32
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"WAYNE",
                "state":"TN",
                "location":"WAYNESBORO",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"NUMEROUS TREES DOWN (OHX)",
                "timeReported":"0433",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -86.6,
                    36.29
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"SUMNER",
                "state":"TN",
                "location":"HENDERSONVILLE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"LARGE TREE DOWN ACROSS POWER LINES (OHX)",
                "timeReported":"0433",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -88.44,
                    36.59
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CALLOWAY",
                "state":"KY",
                "location":"LYNN GROVE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"FARM DAMAGE REPORTED IN LYNN GROVE. (PAH)",
                "timeReported":"0457",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -85.55,
                    37.26
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GREEN",
                "state":"KY",
                "location":"3 W GREENSBURG",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"REPORTED AT GREEN COUNTY... KY POWER OUTAGES AND TREES DOWN COUNTY WIDE. (LMK)",
                "timeReported":"0457",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -85.6,
                    37.23
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"GREEN",
                "state":"KY",
                "location":"3 NNE PIERCE",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SEVERAL TREES AND POWER LINES DOWN ALONG GRAB RD... SOUTHWEST OF GREENSBURG. (LMK)",
                "timeReported":"0503",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -83.81,
                    39.24
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"CLINTON",
                "state":"OH",
                "location":"1 WSW LYNCHBURG",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"SOCIAL MEDIA REPORT OF 25-30 FT FLAG POLE BENT OVER... GARDEN WINDMILL KNOCKED DOWN... AND VAN WINDOW BROKEN FROM FLYING DEBRIS. TIME ESTIMATED FROM RADAR. CORRECTED FO (ILN)",
                "timeReported":"0524",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -83.68,
                    39.23
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HIGHLAND",
                "state":"OH",
                "location":"4 WNW HILLSBORO",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE REPORTED DOWN NEAR ANDERSON RD. AND S.R. 124. TIME ESTIMATED FROM RADAR. (ILN)",
                "timeReported":"0530",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -83.48,
                    39.22
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"HIGHLAND",
                "state":"OH",
                "location":"5 N MARSHALL",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"ROOF DAMAGE TO A BARN ON OVERMAN RD. BETWEEN U.S. 50 AND PETERSBURG RD. TIME ESTIMATED FROM RADAR. (ILN)",
                "timeReported":"0544",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.6,
                    37.21
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"PULASKI",
                "state":"KY",
                "location":"3 NE SCIENCE HILL",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN NEAR THE INTERSECTION OF ETNA CHURCH ROAD AND KENTUCKY HIGHWAY 452 (JKL)",
                "timeReported":"0552",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.55,
                    37.18
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"PULASKI",
                "state":"KY",
                "location":"DABNEY",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN NEAR THE 8000 BLOCK OF KENTUCKY HIGHWAY 39. (JKL)",
                "timeReported":"0554",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -84.42,
                    37.4
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ROCKCASTLE",
                "state":"KY",
                "location":"BRODHEAD",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"ONE LARGE TREE WAS BLOWN DOWN. TIME OF EVENT IS ESTIMATED FROM RADAR DATA. (JKL)",
                "timeReported":"0556",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.7,
                    34.88
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"LAUDERDALE",
                "state":"AL",
                "location":"1 N UNDERWOOD-PETERSVIL",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"TREE DOWN ALONG CR 7 NORTH OF FLORENCE. (HUN)",
                "timeReported":"0600",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.51,
                    34.76
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"COLBERT",
                "state":"AL",
                "location":"4 NNE LEIGHTON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"A POWER POLE REPORTED KNOCKED DOWN AT 9100 2ND STREET. (HUN)",
                "timeReported":"0622",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -87.53,
                    34.76
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"COLBERT",
                "state":"AL",
                "location":"4 N LEIGHTON",
                "marker-symbol":"default_marker",
                "eventType":"2",
                "comments":"POWER POLE KNOCKED DOWN AT 8345 2ND STREET. (HUN)",
                "timeReported":"0623",
                "size":"UNK"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -97.9,
                    33.98
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"JEFFERSON",
                "state":"OK",
                "location":"4 SE RYAN",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"SOCIAL MEDIA REPORT (OUN)",
                "timeReported":"1220",
                "size":"100"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -98.7,
                    28.86
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ATASCOSA",
                "state":"TX",
                "location":"CHARLOTTE",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"QUARTER SIZED HAIL REPORTED BY MPING USER. (EWX)",
                "timeReported":"1133",
                "size":"100"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -99.24,
                    29.56
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"MEDINA",
                "state":"TX",
                "location":"6 SW HILL COUNTRY STATE",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"COCORAHS VOLUNTEER REPORTED GOLF BALL SIZED HAIL. (EWX)",
                "timeReported":"1145",
                "size":"175"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -98.54,
                    28.91
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ATASCOSA",
                "state":"TX",
                "location":"JOURDANTON",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"TIME ESTIMATED WITH RADAR. (EWX)",
                "timeReported":"1146",
                "size":"100"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -98.54,
                    28.91
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ATASCOSA",
                "state":"TX",
                "location":"JOURDANTON",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"(EWX)",
                "timeReported":"1150",
                "size":"100"
            }
        },
        {
            "geometry":{
                "type":"Point",
                "coordinates":[
                    -98.54,
                    28.91
                ]
            },
            "type":"Feature",
            "properties":{
                "county":"ATASCOSA",
                "state":"TX",
                "location":"JOURDANTON",
                "marker-symbol":"default_marker",
                "eventType":"3",
                "comments":"(EWX)",
                "timeReported":"1152",
                "size":"175"
            }
        }
    ]
}